### PR TITLE
Improve client loading and progress reporting, refactoring, fix menus music (closes #2460)

### LINKED ISSUE #2460: Background music ingame + loop
There is a bug that allows you to play the menu music while you are ingame and even loop it while the first one is still playing with using the mute shortcut. Here is how to recreate the bug:

1. Go on any server you like to 
2. Press Ctrl + S to mute the ingame sound 
3. Go into settings and turn the audio back on ( with background music playing )
4. Now the menu music should play while being ingame.
5. Repeat step 2. and the music should loop itself

### PR DESCRIPTION
**Pull request by Robyt3**
- Remove `IClient::GetDebugFont` ~~and use the default font to render the editor tile debug info~~
  - Debug font is loaded lazily because it's most often not used.
  - Performance in editor with default font and lots of tiles with debug info is fine on my machine; not for others, so I reverted to using the debug font, but without depending on the engine client. 
- Add `CComponent::GetInitAmount()` which returns the number of progress ticks, that that particular component will report in its `OnInit` method using `RenderLoading`.
  - Used in existing implementations of OnInit to provide smoother progress report (country flags, menus, skins, background maps)
  - Fixed number of ticks are used for long running methods (especially menus init) to provide some feedback during loading. Values tweaked based on relative execution times on my machine.
  - Game type icons and browser filters are also loaded during loading screen.
- Remove unused `CMenus::m_CurrentVideoFormat` and `UpdateVideoFormats`. Used bubble sort most inefficiently without even being used.
- Initialize editor after client components instead of before, to get the loading screen up sooner.
- Fix some naming, minor restructuring.
- UI: Show full progress bar faintly behind the filling one:
grafik
- Total startup time hasn't really changed, but the time where the screen is just white should be much shorter now.

This should address the technical items of #2403.

Also fixes incorrect menu music states and duplicated music playback when ingame (closes #2460).

### CODE REVIEW

**Comment by Robyt3** [comment]
Shouldn't it just say "Teeworlds" instead of "Loading"? It should already be clear that it's loading something, because there is a progress bar.

grafik

Or even better with this image:
gui_logo

**Comment by Dune-jr** [comment]
> Shouldn't it just say "Teeworlds" instead of "Loading"? It should already be clear that it's loading something, because there is a progress bar.
> 
> grafik

I think that's a good idea.

> Or even better with this image:
> gui_logo

Doesn't sound too easy to integrate, maybe someone will have a design idea :)
cc @Zatline

**Comment by fokkonaut** [comment]
%?

**Comment by Robyt3** [comment]
> %?

Yeah, I could add that at the very least.

It's probably not useful to show what's currently being loaded thou, since it only takes a second anyway.

**Comment by axblk** [comment]
The text-renderer is way too slow for the editor layers. When zooming out it's running with 10 fps on my intel igpu vs 170 fps with debug font. I'm working on some optimizations for the text-renderer but it's kinda hard to get better performance than with `QuadsText()`.

**Comment by Robyt3** [comment]
> 
> 
> The text-renderer is way too slow for the editor layers. When zooming out it's running with 10 fps on my intel igpu vs 170 fps with debug font. I'm working on some optimizations for the text-renderer but it's kinda hard to get better performance than with `QuadsText()`.

Could just deactivate while zooming for now?

**Comment by Dune-jr** [comment]
I remember printing a number on each tile and it put my home computer to its knees, without zooming out more than ingame. It's probably not a good idea to use the TextRenderer heavily, in its current state.

**Comment by axblk** [comment]
With default editor zoom level it's at ~20 fps and even with 1:1 it's below 60. Right now the text renderer is just not suited for this.

**Comment by Robyt3** [comment]
> With default editor zoom level it's at ~20 fps and even with 1:1 it's below 60. Right now the text renderer is just not suited for this.

I see. I'll revert it to the debug font for now, then.

**Comment by Robyt3** [comment]
Logo looks a bit too out of place for the loading screen. I'll leave that to the designers.

grafik

Current state:
grafik

**Comment by Dune-jr** [comment]
The percentage will get hidden when the loading bar is half-way right?

**Comment by Robyt3** [comment]
It changes color to dark grey after 50%.

**Comment by heinrich5991** [comment]
I like this a lot. 👍

File: src/game/client/components/menus.cpp [hunk 1]
```diff
@@ -1252,19 +1263,26 @@ void CMenus::RenderLoading()
...
+	float Spacing = 40.0f;
+	float Rounding = 5.0f;
+	CUIRect FullBar = {x+Spacing, y+h-75.0f, w-2*Spacing, 25.0f};
+	RenderTools()->DrawRoundRect(&FullBar, vec4(1.0f, 1.0f, 1.0f, 0.10f), Rounding);
+	CUIRect FillingBar = FullBar;
+	FillingBar.w = (FullBar.w-2*Rounding)*Percent+2*Rounding;
+	RenderTools()->DrawRoundRect(&FillingBar, vec4(1.0f, 1.0f, 1.0f, 0.75f), Rounding);
+
+	if(Percent > 0.5)
+		TextRender()->TextColor(0.2f, 0.2f, 0.2f, 1.0f);
```
Comment (Dune-jr) [inline src/game/client/components/menus.cpp]: Nitpicking again, but it would be nice to put a white outline (`TextOutline`) on black text (instead of black on black). At the moment black looks fatter because of that as far as I can tell.

**Comment by Robyt3** [comment]
That looks cleaner @Dune-jr:

grafik

**Comment by oy** [comment]
Loads for me with release version 25% slower than before, but that's just 150ms so I don't really notice.
How's it for others/slower machines?

**Comment by Robyt3** [comment]
780ms to bring up the graphics. Then 200ms for sound, input, font rendering until Gameclient::OnInit is called (white screen). Gameclient init takes 1360ms. Gameclient init is expected to be slightly longer in favor of shorter white screen time and also because more components are preloaded.
The time to init the graphics is mostly spent in SDL_CreateWindow. Googling tells me it's because I have NVIDIA GeForce which tries to match teeworlds with a database of specific application settings using a linear search.

File: src/game/client/components/menus.cpp [hunk 2]
```diff
@@ -2502,7 +2502,8 @@ void CMenus::RenderBackground()
 	Graphics()->TextureClear();
 	Graphics()->QuadsBegin();
 		float Size = 15.0f;
-		float OffsetTime = fmod(Client()->LocalTime()*0.15f, 2.0f);
+		static int64 s_MenuBackgroundStart = time_get();
+		float OffsetTime = fmod((time_get()-s_MenuBackgroundStart)*0.15f/time_freq(), 2.0f);
```
Comment (oy) [inline src/game/client/components/menus.cpp]: Try not to use time_get in a render function

Comment (Robyt3) [reply src/game/client/components/menus.cpp]: What else to use thou? Or where to move this timer? `Client()->LocalTime()` is not running at that point because `RenderBackground` is called by `RenderLoading` which is running outside of the game/render loop that updates the local time in [client.cpp#L2141](https://github.com/Robyt3/teeworlds/blob/afda8d5923c60fa381de9c5f912579d74b5cad17/src/engine/client/client.cpp#L2141). `IClient` would need to expose a "UpdateLocalTime" method to the gameclient so it can update the local time itself from `RenderLoading`.

Comment (oy) [reply src/game/client/components/menus.cpp]: Hm, the whole thing is kinda hacky as you hijack the rendering process in this pr. And f.e. don't use the double buffering which might lead to problems for some users.
About the timer: You could transfer it to the RenderLoading function which is only used during the initilaization, and so keep the normal process clean. That includes the [Clear ](https://github.com/teeworlds/teeworlds/pull/2459/files#diff-cad6690c312d4ab80e91a046cdbb5becR2495) call too, which shouldn't be there during the normal process.
