### PR TITLE
Fix button order in demo browser (closed #2679)

### LINKED ISSUE #2679: Fix position of refresh button in demo browser
The position of the refresh button in the demo browser changes depending if a demo or folder is selected.
It should keep its position.

### PR DESCRIPTION
**Pull request by ChillerDragon**
demo_buttons
Do not move the refresh button when switching from demofile to directory

### CODE REVIEW

File: src/game/client/components/menus_demo.cpp [hunk 1]
```diff
@@ -623,17 +623,9 @@ void CMenus::RenderDemoList(CUIRect MainView)
...
-	if(DoButton_Menu(&s_RefreshButton, Localize("Refresh"), 0, &Button) || (Input()->KeyPress(KEY_R) && (Input()->KeyIsPressed(KEY_LCTRL) || Input()->KeyIsPressed(KEY_RCTRL))))
-	{
-		DemolistPopulate();
-		DemolistOnUpdate(false);
-	}
-
 	if(!m_DemolistSelectedIsDir)
 	{
-		BottomView.VSplitLeft(Spacing, 0, &BottomView);
+		BottomView.VSplitLeft(0, 0, &BottomView);
```
Comment (Robyt3) [inline src/game/client/components/menus_demo.cpp:628]: Redundant.

Comment (ChillerDragon) [reply src/game/client/components/menus_demo.cpp]: thanks fixed :)
