### PR TITLE
Fix integer overflow when computing tilemap size. Fixes #2071

### LINKED ISSUE #2071: Integer overflow and null pointer dereference in CMap::Load() in engine/shared/map.cpp
Hello Teeworlds dev team,

There is an integer overflow in CMap::Load() which can lead to a buffer overflow.

```C++
CTile *pTiles = static_cast<CTile *>(mem_alloc(pTilemap->m_Width * pTilemap->m_Height * sizeof(CTile), 1));

// extract original tile data
int i = 0;
CTile *pSavedTiles = static_cast<CTile *>(m_DataFile.GetData(pTilemap->m_Data));
while(i < pTilemap->m_Width * pTilemap->m_Height)
{
	for(unsigned Counter = 0; Counter <= pSavedTiles->m_Skip && i < pTilemap->m_Width * pTilemap->m_Height; Counter++)
	{
		pTiles[i] = *pSavedTiles;
		pTiles[i++].m_Skip = 0;
	}

	pSavedTiles++;
}
```

`pTilemap->m_Width` and `pTilemap->m_Height` can be arbitrary integers and there is no check for an integer overflow when multiplying these integers with each other and with `sizeof(CTile)`. 

Also there is no check if mem_alloc returns NULL which can lead to a null pointer dereference.

Regards,

Mans van Someren

http://whatthebug.net/

### PR DESCRIPTION
**Pull request by Dune-jr**
Taken from https://github.com/teeworlds/teeworlds/pull/2074, fixes #2071

### CODE REVIEW

File: src/engine/shared/map.cpp [hunk 1]
```diff
@@ -55,7 +56,14 @@ class CMap : public IEngineMap
 					
 					if(pTilemap->m_Version > 3)
 					{
+						if(!((pTilemap->m_Width <= INT_MAX / 2 - 1) && (pTilemap->m_Height <= INT_MAX / 2 - 1)))
```
Comment (oy) [inline src/engine/shared/map.cpp]: You can still have an integer overflow. F.e.: (INT_MAX/2-2)*(INT_MAX/2-2) > INT_MAX

Comment (Dune-jr) [reply src/engine/shared/map.cpp]: ugh, I took the wrong half of #2074

**Comment by Dune-jr** [comment]
- Fixed the commit fixing #2071 with @oy's instructions
- Retrieved e086f4b35b1adf7edc35b4ad332dc7ed1edc5988 to fix #2073
