### PR TITLE
Fix several statboard issues

### LINKED ISSUE #2155: Statsboard doesn't clear on game restart
screenshot_2019-06-16_11-31-51
screenshot_2019-06-16_11-31-53

### PR DESCRIPTION
**Pull request by axblk**
- Statboard does not list all players (caused by https://github.com/teeworlds/teeworlds/commit/cb79d646a8afdd546391725714932c44ac4355af)
- Stats for the particular ID are not reset when a new player enters
- Closes #2155
- FPM value should only consider ingame ticks (not in spec and not paused)

The fix for #2155 is rather hackish, but it seems to be the only way to detect gameover and restarting on client side. The game start tick changes in 3 cases: new game, paused or countdown. You have to make sure that the game is not paused when the game start tick changes. The game can start with a countdown, but it must not be a countdown to continue after a pause.

### CODE REVIEW

**Comment by Dune-jr** [comment]
Thanks! Much needed fixes and cleanup.

File: src/game/client/components/stats.h [hunk 1]
```diff
@@ -29,6 +57,15 @@ class CStats: public CComponent
...
+	void OnMatchStart();
+	void OnFlagGrab(int ClientID);
+	void OnFlagCapture(int ClientID);
+	void OnPlayerEnter(int ClientID, int Team);
+	void OnPlayerLeave(int ClientID);
+
+	const CPlayerStats *GetPlayerStats(int ClientID) const { return &m_aStats[ClientID]; }
 };
 
 #endif
```
Comment (ChillerDragon) [inline src/game/client/components/stats.h]: Newline would be nice. Also the whole file seems to have bugged line endings that show a ^M in the git diff.

**Comment by Sonix-** [comment]
Since I cant check, are the weapon kd columns aligned properly to each icon? In the actual version they are kinda buggy and misaligned
