### PR TITLE
Fix tees being stuck in each other (closes #1261)

### LINKED ISSUE #1261: Collision code makes tees stuck in each other for several ticks
What the title says. It's likely that the culprit for this is the fix for tees passing through each other.

### PR DESCRIPTION
**Pull request by fokkonaut**

### CODE REVIEW

File: src/game/gamecore.cpp [hunk 1]
```diff
@@ -376,7 +376,7 @@ void CCharacterCore::Move()
 				if(!pCharCore || pCharCore == this)
 					continue;
 				float D = distance(Pos, pCharCore->m_Pos);
-				if(D < PhysSize && D > 0.0f)
+				if((D < PhysSize && D > 0.0f) || (D <= 0.001f && D >= -0.001f))
```
Comment (oy) [inline src/game/gamecore.cpp]: Hm, that looks odd, `D` shouldn't be negative at all.

Comment (fokkonaut) [reply src/game/gamecore.cpp]: I took the code that DDNet had in for several years, it works reliably.

Comment (fokkonaut) [reply src/game/gamecore.cpp]: https://github.com/ddnet/ddnet/blob/af6d463fb6ed356e7e5bdede15fa54646284f17c/src/game/gamecore.cpp#L505

Comment (Dune-jr) [reply src/game/gamecore.cpp]: This would imply that sqrtf can return a negative value: 
```cpp
template<typename T>
inline T distance(const vector2_base<T> &a, const vector2_base<T> &b)
{
	return length(a-b);
}
inline float length(const vector2_base<float> &a)
{
	return sqrtf(a.x*a.x + a.y*a.y);
}
```

Comment (fokkonaut) [reply src/game/gamecore.cpp]: shall i remove the negative check?

Comment (fokkonaut) [reply src/game/gamecore.cpp]: Okay, removed the negative check

Comment (oy) [reply src/game/gamecore.cpp]: There could be a negative zero as result.
